name: house4house
version: "1.0.0"
config-version: 2

profile: house4house

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  caop_year: 2025

on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS staging_dbt"
  - "CREATE SCHEMA IF NOT EXISTS silver_market"
  - "CREATE SCHEMA IF NOT EXISTS silver_properties"
  - "CREATE SCHEMA IF NOT EXISTS silver_geo"
  - "CREATE SCHEMA IF NOT EXISTS silver_location"
  - "CREATE SCHEMA IF NOT EXISTS gold_analytics"

models:
  house4house:
    staging:
      +materialized: view
      +schema: staging_dbt
    silver:
      +materialized: table
      market:
        +schema: silver_market
      properties:
        +schema: silver_properties
      geo:
        +schema: silver_geo
      location:
        +schema: silver_location
    gold:
      +materialized: table
      +schema: gold_analytics
