MUNICIPALITIES: list[CRUSMunicipalityConfig] = [
    # District 01
    CRUSMunicipalityConfig("0101", "Agueda", "gmgml:CRUS_Agueda_V"),
    CRUSMunicipalityConfig("0102", "Albergaria-a-Velha", "gmgml:CRUS_Albergaria_a_Velha_V"),
    CRUSMunicipalityConfig("0103", "Anadia", "gmgml:CRUS_Anadia_V"),
    CRUSMunicipalityConfig("0104", "Arouca", "gmgml:CRUS_Arouca_V"),
    CRUSMunicipalityConfig("0105", "Aveiro", "gmgml:CRUS_Aveiro_V"),
    CRUSMunicipalityConfig("0106", "Castelo de Paiva", "gmgml:CRUS_Castelo_de_Paiva_V"),
    CRUSMunicipalityConfig("0107", "Espinho", "gmgml:CRUS_Espinho_V"),
    CRUSMunicipalityConfig("0108", "Estarreja", "gmgml:CRUS_Estarreja_V"),
    CRUSMunicipalityConfig("0109", "Santa Maria da Feira", "gmgml:CRUS_Santa_Maria_da_Feira_V"),
    CRUSMunicipalityConfig("0110", "Ilhavo", "gmgml:CRUS_Ilhavo_V"),
    CRUSMunicipalityConfig("0111", "Mealhada", "gmgml:CRUS_Mealhada_V"),
    CRUSMunicipalityConfig("0112", "Murtosa", "gmgml:CRUS_Murtosa_V"),
    CRUSMunicipalityConfig("0113", "Oliveira de Azemeis", "gmgml:CRUS_Oliveira_de_Azemeis_V"),
    CRUSMunicipalityConfig("0114", "Oliveira do Bairro", "gmgml:CRUS_Oliveira_do_Bairro_V"),
    CRUSMunicipalityConfig("0115", "Ovar", "gmgml:CRUS_Ovar_V"),
    CRUSMunicipalityConfig("0116", "Sao Joao da Madeira", "gmgml:CRUS_Sao_Joao_da_Madeira_V"),
    CRUSMunicipalityConfig("0117", "Sever do Vouga", "gmgml:CRUS_Sever_do_Vouga_V"),
    CRUSMunicipalityConfig("0118", "Vagos", "gmgml:CRUS_Vagos_V"),
    CRUSMunicipalityConfig("0119", "Vale de Cambra", "gmgml:CRUS_Vale_de_Cambra_V"),
    # District 02
    CRUSMunicipalityConfig("0201", "Aljustrel", "gmgml:CRUS_Aljustrel_V"),
    CRUSMunicipalityConfig("0202", "Almodavar", "gmgml:CRUS_Almodovar_V"),
    CRUSMunicipalityConfig("0203", "Alvito", "gmgml:CRUS_Alvito_V"),
    CRUSMunicipalityConfig("0204", "Barrancos", "gmgml:CRUS_Barrancos_V"),
    CRUSMunicipalityConfig("0205", "Beja", "gmgml:CRUS_Beja_V"),
    CRUSMunicipalityConfig("0206", "Castro Verde", "gmgml:CRUS_Castro_Verde_V"),
    CRUSMunicipalityConfig("0207", "Cuba", "gmgml:CRUS_Cuba_V"),
    CRUSMunicipalityConfig("0208", "Ferreira do Alentejo", "gmgml:CRUS_Ferreira_do_Alentejo_V"),
    CRUSMunicipalityConfig("0209", "Mertola", "gmgml:CRUS_Mertola_V"),
    CRUSMunicipalityConfig("0210", "Moura", "gmgml:CRUS_Moura_V"),
    CRUSMunicipalityConfig("0211", "Odemira", "gmgml:CRUS_Odemira_V"),
    CRUSMunicipalityConfig("0212", "Ourique", "gmgml:CRUS_Ourique_V"),
    CRUSMunicipalityConfig("0213", "Serpa", "gmgml:CRUS_Serpa_V"),
    CRUSMunicipalityConfig("0214", "Vidigueira", "gmgml:CRUS_Vidigueira_V"),
    # District 03
    CRUSMunicipalityConfig("0301", "Amares", "gmgml:CRUS_Amares_V"),
    CRUSMunicipalityConfig("0302", "Barcelos", "gmgml:CRUS_Barcelos_V"),
    CRUSMunicipalityConfig("0303", "Braga", "gmgml:CRUS_Braga_V"),
    CRUSMunicipalityConfig("0304", "Cabeceiras de Basto", "gmgml:CRUS_Cabeceiras_de_Basto_V"),
    CRUSMunicipalityConfig("0305", "Celorico de Basto", "gmgml:CRUS_Celorico_de_Basto_V"),
    CRUSMunicipalityConfig("0306", "Esposende", "gmgml:CRUS_Esposende_V"),
    CRUSMunicipalityConfig("0307", "Fafe", "gmgml:CRUS_Fafe_V"),
    CRUSMunicipalityConfig("0308", "Guimaraes", "gmgml:CRUS_Guimaraes_V"),
    CRUSMunicipalityConfig("0309", "Povoa de Lanhoso", "gmgml:CRUS_Povoa_de_Lanhoso_V"),
    CRUSMunicipalityConfig("0310", "Terras de Bouro", "gmgml:CRUS_Terras_de_Bouro_V"),
    CRUSMunicipalityConfig("0311", "Vieira do Minho", "gmgml:CRUS_Vieira_do_Minho_V"),
    CRUSMunicipalityConfig("0312", "Vila Nova de Famalicao", "gmgml:CRUS_Vila_Nova_de_Famalicao_V"),
    CRUSMunicipalityConfig("0313", "Vila Verde", "gmgml:CRUS_Vila_Verde_V"),
    CRUSMunicipalityConfig("0314", "Vizela", "gmgml:CRUS_Vizela_V"),
    # District 04
    CRUSMunicipalityConfig("0401", "Alfandega da Fe", "gmgml:CRUS_Alfandega_da_Fe_V"),
    CRUSMunicipalityConfig("0402", "Braganca", "gmgml:CRUS_Braganca_V"),
    CRUSMunicipalityConfig("0403", "Carrazeda de Ansiaes", "gmgml:CRUS_Carrazeda_de_Ansiaes_V"),
    CRUSMunicipalityConfig("0404", "Freixo de Espada a Cinta", "gmgml:CRUS_Freixo_de_Espada_a_Cinta_V"),
    CRUSMunicipalityConfig("0405", "Macedo de Cavaleiros", "gmgml:CRUS_Macedo_de_Cavaleiros_V"),
    CRUSMunicipalityConfig("0406", "Miranda do Douro", "gmgml:CRUS_Miranda_do_Douro_V"),
    CRUSMunicipalityConfig("0407", "Mirandela", "gmgml:CRUS_Mirandela_V"),
    CRUSMunicipalityConfig("0408", "Mogadouro", "gmgml:CRUS_Mogadouro_V"),
    CRUSMunicipalityConfig("0409", "Torre de Moncorvo", "gmgml:CRUS_Torre_de_Moncorvo_V"),
    CRUSMunicipalityConfig("0410", "Vila Flor", "gmgml:CRUS_Vila_Flor_V"),
    CRUSMunicipalityConfig("0411", "Vimioso", "gmgml:CRUS_Vimioso_V"),
    CRUSMunicipalityConfig("0412", "Vinhais", "gmgml:CRUS_Vinhais_V"),
    # District 05
    CRUSMunicipalityConfig("0501", "Belmonte", "gmgml:CRUS_Belmonte_V"),
    CRUSMunicipalityConfig("0502", "Castelo Branco", "gmgml:CRUS_Castelo_Branco_V"),
    CRUSMunicipalityConfig("0503", "Covilha", "gmgml:CRUS_Covilha_V"),
    CRUSMunicipalityConfig("0504", "Fundao", "gmgml:CRUS_Fundao_V"),
    CRUSMunicipalityConfig("0505", "Idanha-a-Nova", "gmgml:CRUS_Idanha_a_Nova_V"),
    CRUSMunicipalityConfig("0506", "Oleiros", "gmgml:CRUS_Oleiros_V"),
    CRUSMunicipalityConfig("0507", "Penamacor", "gmgml:CRUS_Penamacor_V"),
    CRUSMunicipalityConfig("0508", "Proenca-a-Nova", "gmgml:CRUS_Proenca_a_Nova_V"),
    CRUSMunicipalityConfig("0509", "Serta", "gmgml:CRUS_Serta_V"),
    CRUSMunicipalityConfig("0510", "Vila de Rei", "gmgml:CRUS_Vila_de_Rei_V"),
    CRUSMunicipalityConfig("0511", "Vila Velha de Rodao", "gmgml:CRUS_Vila_Velha_de_Rodao_V"),
    # District 06
    CRUSMunicipalityConfig("0601", "Arganil", "gmgml:CRUS_Arganil_V"),
    CRUSMunicipalityConfig("0602", "Cantanhede", "gmgml:CRUS_Cantanhede_V"),
    CRUSMunicipalityConfig("0603", "Coimbra", "gmgml:CRUS_Coimbra_V"),
    CRUSMunicipalityConfig("0604", "Condeixa-a-Nova", "gmgml:CRUS_Condeixa_a_Nova_V"),
    CRUSMunicipalityConfig("0605", "Figueira da Foz", "gmgml:CRUS_Figueira_da_Foz_V"),
    CRUSMunicipalityConfig("0606", "Gois", "gmgml:CRUS_Gois_V"),
    CRUSMunicipalityConfig("0607", "Lousa", "gmgml:CRUS_Lousa_V"),
    CRUSMunicipalityConfig("0608", "Mira", "gmgml:CRUS_Mira_V"),
    CRUSMunicipalityConfig("0609", "Miranda do Corvo", "gmgml:CRUS_Miranda_do_Corvo_V"),
    CRUSMunicipalityConfig("0610", "Montemor-o-Velho", "gmgml:CRUS_Montemor_o_Velho_V"),
    CRUSMunicipalityConfig("0611", "Oliveira do Hospital", "gmgml:CRUS_Oliveira_do_Hospital_V"),
    CRUSMunicipalityConfig("0612", "Pampilhosa da Serra", "gmgml:CRUS_Pampilhosa_da_Serra_V"),
    CRUSMunicipalityConfig("0613", "Penacova", "gmgml:CRUS_Penacova_V"),
    CRUSMunicipalityConfig("0614", "Penela", "gmgml:CRUS_Penela_V"),
    CRUSMunicipalityConfig("0615", "Soure", "gmgml:CRUS_Soure_V"),
    CRUSMunicipalityConfig("0616", "Tabua", "gmgml:CRUS_Tabua_V"),
    CRUSMunicipalityConfig("0617", "Vila Nova de Poiares", "gmgml:CRUS_Vila_Nova_de_Poiares_V"),
    # District 07
    CRUSMunicipalityConfig("0701", "Alandroal", "gmgml:CRUS_Alandroal_V"),
    CRUSMunicipalityConfig("0702", "Arraiolos", "gmgml:CRUS_Arraiolos_V"),
    CRUSMunicipalityConfig("0703", "Borba", "gmgml:CRUS_Borba_V"),
    CRUSMunicipalityConfig("0704", "Estremoz", "gmgml:CRUS_Estremoz_V"),
    CRUSMunicipalityConfig("0705", "Evora", "gmgml:CRUS_Evora_V"),
    CRUSMunicipalityConfig("0706", "Montemor-o-Novo", "gmgml:CRUS_Montemor_o_Novo_V"),
    CRUSMunicipalityConfig("0707", "Mora", "gmgml:CRUS_Mora_V"),
    CRUSMunicipalityConfig("0708", "Mourao", "gmgml:CRUS_Mourao_V"),
    CRUSMunicipalityConfig("0709", "Portel", "gmgml:CRUS_Portel_V"),
    CRUSMunicipalityConfig("0710", "Redondo", "gmgml:CRUS_Redondo_V"),
    CRUSMunicipalityConfig("0711", "Reguengos de Monsaraz", "gmgml:CRUS_Reguengos_de_Monsaraz_V"),
    CRUSMunicipalityConfig("0712", "Vendas Novas", "gmgml:CRUS_Vendas_Novas_V"),
    CRUSMunicipalityConfig("0713", "Viana do Alentejo", "gmgml:CRUS_Viana_do_Alentejo_V"),
    CRUSMunicipalityConfig("0714", "Vila Vicosa", "gmgml:CRUS_Vila_Vicosa_V"),
    # District 08
    CRUSMunicipalityConfig("0801", "Albufeira", "gmgml:CRUS_Albufeira_V"),
    CRUSMunicipalityConfig("0802", "Alcoutim", "gmgml:CRUS_Alcoutim_V"),
    CRUSMunicipalityConfig("0803", "Aljezur", "gmgml:CRUS_Aljezur_V"),
    CRUSMunicipalityConfig("0804", "Castro Marim", "gmgml:CRUS_Castro_Marim_V"),
    CRUSMunicipalityConfig("0805", "Faro", "gmgml:CRUS_Faro_V"),
    CRUSMunicipalityConfig("0806", "Lagoa", "gmgml:CRUS_Lagoa_V"),
    CRUSMunicipalityConfig("0807", "Lagos", "gmgml:CRUS_Lagos_V"),
    CRUSMunicipalityConfig("0808", "Loule", "gmgml:CRUS_Loule_V"),
    CRUSMunicipalityConfig("0809", "Monchique", "gmgml:CRUS_Monchique_V"),
    CRUSMunicipalityConfig("0810", "Olhao", "gmgml:CRUS_Olhao_V"),
    CRUSMunicipalityConfig("0811", "Portimao", "gmgml:CRUS_Portimao_V"),
    CRUSMunicipalityConfig("0812", "Sao Bras de Alportel", "gmgml:CRUS_Sao_Bras_de_Alportel_V"),
    CRUSMunicipalityConfig("0813", "Silves", "gmgml:CRUS_Silves_V"),
    CRUSMunicipalityConfig("0814", "Tavira", "gmgml:CRUS_Tavira_V"),
    CRUSMunicipalityConfig("0815", "Vila do Bispo", "gmgml:CRUS_Vila_do_Bispo_V"),
    CRUSMunicipalityConfig("0816", "Vila Real de Santo Antonio", "gmgml:CRUS_Vila_Real_de_Santo_Antonio_V"),
    # District 09
    CRUSMunicipalityConfig("0901", "Aguiar da Beira", "gmgml:CRUS_Aguiar_da_Beira_V"),
    CRUSMunicipalityConfig("0902", "Almeida", "gmgml:CRUS_Almeida_V"),
    CRUSMunicipalityConfig("0903", "Celorico da Beira", "gmgml:CRUS_Celorico_da_Beira_V"),
    CRUSMunicipalityConfig("0904", "Figueira de Castelo Rodrigo", "gmgml:CRUS_Figueira_de_Castelo_Rodrigo_V"),
    CRUSMunicipalityConfig("0905", "Fornos de Algodres", "gmgml:CRUS_Fornos_de_Algodres_V"),
    CRUSMunicipalityConfig("0906", "Gouveia", "gmgml:CRUS_Gouveia_V"),
    CRUSMunicipalityConfig("0907", "Guarda", "gmgml:CRUS_Guarda_V"),
    CRUSMunicipalityConfig("0908", "Manteigas", "gmgml:CRUS_Manteigas_V"),
    CRUSMunicipalityConfig("0909", "Meda", "gmgml:CRUS_Meda_V"),
    CRUSMunicipalityConfig("0910", "Pinhel", "gmgml:CRUS_Pinhel_V"),
    CRUSMunicipalityConfig("0911", "Sabugal", "gmgml:CRUS_Sabugal_V"),
    CRUSMunicipalityConfig("0912", "Seia", "gmgml:CRUS_Seia_V"),
    CRUSMunicipalityConfig("0913", "Trancoso", "gmgml:CRUS_Trancoso_V"),
    CRUSMunicipalityConfig("0914", "Vila Nova de Foz Coa", "gmgml:CRUS_Vila_Nova_de_Foz_Coa_V"),
    # District 10
    CRUSMunicipalityConfig("1002", "Alvaiazere", "gmgml:CRUS_Alvaiazere_V"),
    CRUSMunicipalityConfig("1003", "Ansiao", "gmgml:CRUS_Ansiao_V"),
    CRUSMunicipalityConfig("1004", "Batalha", "gmgml:CRUS_Batalha_V"),
    CRUSMunicipalityConfig("1005", "Bombarral", "gmgml:CRUS_Bombarral_V"),
    CRUSMunicipalityConfig("1006", "Caldas da Rainha", "gmgml:CRUS_Caldas_da_Rainha_V"),
    CRUSMunicipalityConfig("1007", "Castanheira de Pera", "gmgml:CRUS_Castanheira_de_Pera_V"),
    CRUSMunicipalityConfig("1008", "Figueiro dos Vinhos", "gmgml:CRUS_Figueiro_dos_Vinhos_V"),
    CRUSMunicipalityConfig("1009", "Leiria", "gmgml:CRUS_Leiria_V"),
    CRUSMunicipalityConfig("1010", "Marinha Grande", "gmgml:CRUS_Marinha_Grande_V"),
    CRUSMunicipalityConfig("1011", "Nazare", "gmgml:CRUS_Nazare_V"),
    CRUSMunicipalityConfig("1012", "Obidos", "gmgml:CRUS_Obidos_V"),
    CRUSMunicipalityConfig("1013", "Pedrogao Grande", "gmgml:CRUS_Pedrogao_Grande_V"),
    CRUSMunicipalityConfig("1014", "Peniche", "gmgml:CRUS_Peniche_V"),
    CRUSMunicipalityConfig("1015", "Pombal", "gmgml:CRUS_Pombal_V"),
    CRUSMunicipalityConfig("1016", "Porto de Mos", "gmgml:CRUS_Porto_de_Mos_V"),
    # District 11
    CRUSMunicipalityConfig("1101", "Alenquer", "gmgml:CRUS_Alenquer_V"),
    CRUSMunicipalityConfig("1102", "Amadora", "gmgml:CRUS_Arruda_dos_Vinhos_V"),
    CRUSMunicipalityConfig("1103", "Arruda dos Vinhos", "gmgml:CRUS_Azambuja_V"),
    CRUSMunicipalityConfig("1104", "Azambuja", "gmgml:CRUS_Cadaval_V"),
    CRUSMunicipalityConfig("1105", "Cadaval", "gmgml:CRUS_Cascais_V"),
    CRUSMunicipalityConfig("1106", "Lisboa", "gmgml:CRUS_Lisboa_V"),
    CRUSMunicipalityConfig("1107", "Loures", "gmgml:CRUS_Loures_V"),
    CRUSMunicipalityConfig("1109", "Mafra", "gmgml:CRUS_Mafra_V"),
    CRUSMunicipalityConfig("1110", "Oeiras", "gmgml:CRUS_Oeiras_V"),
    CRUSMunicipalityConfig("1111", "Sintra", "gmgml:CRUS_Sintra_V"),
    CRUSMunicipalityConfig("1112", "Sobral de Monte Agraco", "gmgml:CRUS_Sobral_de_Monte_Agraco_V"),
    CRUSMunicipalityConfig("1113", "Torres Vedras", "gmgml:CRUS_Torres_Vedras_V"),
    CRUSMunicipalityConfig("1114", "Vila Franca de Xira", "gmgml:CRUS_Vila_Franca_de_Xira_V"),
    CRUSMunicipalityConfig("1115", "Cascais", "gmgml:CRUS_Amadora_V"),
    CRUSMunicipalityConfig("1116", "Odivelas", "gmgml:CRUS_Odivelas_V"),
    # District 12
    CRUSMunicipalityConfig("1203", "Avis", "gmgml:CRUS_Avis_V"),
    CRUSMunicipalityConfig("1204", "Campo Maior", "gmgml:CRUS_Campo_Maior_V"),
    CRUSMunicipalityConfig("1205", "Castelo de Vide", "gmgml:CRUS_Castelo_de_Vide_V"),
    CRUSMunicipalityConfig("1206", "Crato", "gmgml:CRUS_Crato_V"),
    CRUSMunicipalityConfig("1207", "Elvas", "gmgml:CRUS_Elvas_V"),
    CRUSMunicipalityConfig("1209", "Gaviao", "gmgml:CRUS_Gaviao_V"),
    CRUSMunicipalityConfig("1210", "Marvao", "gmgml:CRUS_Marvao_V"),
    CRUSMunicipalityConfig("1211", "Monforte", "gmgml:CRUS_Monforte_V"),
    CRUSMunicipalityConfig("1212", "Nisa", "gmgml:CRUS_Nisa_V"),
    # District 13
    CRUSMunicipalityConfig("1304", "Gondomar", "gmgml:CRUS_Gondomar_V"),
    CRUSMunicipalityConfig("1311", "Penafiel", "gmgml:CRUS_Penafiel_V"),
    # District 14
    CRUSMunicipalityConfig("1401", "Abrantes", "gmgml:CRUS_Abrantes_V"),
    CRUSMunicipalityConfig("1403", "Almeirim", "gmgml:CRUS_Almeirim_V"),
    CRUSMunicipalityConfig("1413", "Macao", "gmgml:CRUS_Macao_V"),
    CRUSMunicipalityConfig("1417", "Sardoal", "gmgml:CRUS_Sardoal_V"),
    # District 15
    CRUSMunicipalityConfig("1501", "Alcacer do Sal", "gmgml:CRUS_Alcacer_do_Sal_V"),
    CRUSMunicipalityConfig("1505", "Grandola", "gmgml:CRUS_Grandola_V"),
    # District 16
    CRUSMunicipalityConfig("1604", "Moncao", "gmgml:CRUS_Moncao_V"),
    CRUSMunicipalityConfig("1608", "Valenca", "gmgml:CRUS_Valenca_V"),
    # District 17
    CRUSMunicipalityConfig("1702", "Boticas", "gmgml:CRUS_Boticas_V"),
    CRUSMunicipalityConfig("1710", "Sabrosa", "gmgml:CRUS_Sabrosa_V"),
    # District 18
    CRUSMunicipalityConfig("1807", "Moimenta da Beira", "gmgml:CRUS_Moimenta_da_Beira_V"),
    CRUSMunicipalityConfig("1824", "Vouzela", "gmgml:CRUS_Vouzela_V"),
]